### ISSUE TITLE
Unable to switch back from SSH/HTTP to Custom

### ISSUE THREAD

**Issue by jlwt90** [mohamicorp/stash-jenkins-postreceive-webhook#183]
Hello, I encountered the following issue:

**1) open this form**
![screen shot 2017-03-03 at 17 51 05](https://cloud.githubusercontent.com/assets/25281597/23544347/0345490a-003a-11e7-9010-2f7a2d2cabba.png)

**2) change type to HTTP (or SSH)**
![screen shot 2017-03-03 at 17 56 12](https://cloud.githubusercontent.com/assets/25281597/23544519/b40a8868-003a-11e7-91e7-930985ea2bbc.png)

**3) change back to Custom**
![screen shot 2017-03-03 at 17 56 33](https://cloud.githubusercontent.com/assets/25281597/23544534/c160bdb6-003a-11e7-9d74-cb3cebace0af.png)

As you may notice, the field is still disabled.
So I checked the JS ([jenkins.js](https://github.com/Nerdwin15/stash-jenkins-postreceive-webhook/blob/master/src/main/resources/static/jenkins.js#L50))

I think `.removeProp("disabled")` doesn't work here. It should be fine if we change it to `.prop("disabled", false)`.

Does anyone find the same issue?

**Comment by thrownullpointer** [comment]
I have not seen this before. What browser are you using? What version of stash or bitbutcket?

**Comment by jlwt90** [comment]
Hi @thrownullpointer ,

Thanks for your reply. I am using Atlassian Bitbucket v4.8.6.

Doesn't work for the browsers below.
Firefox Developer Edition: 55.0b3
Safari: Version 10.0 (12602.1.50.0.10)
Chrome: Version 58.0.3029.110 (64-bit)

Thanks!

**Comment by SirJane** [comment]
I have been experiencing this with Bitbucket v4.12, and Firefox 54.0.1 (and 2-3 earlier versions).
There doesn't seem to be a workaround, except hit "cancel" and start over.

**Comment by marvinthepa** [comment]
I fixed this in #194, see https://github.com/Nerdwin15/stash-jenkins-postreceive-webhook/pull/194/files#diff-6127cafb8b70cf899b75a802223d3d14

**Comment by alexBraidwood** [comment]
Committed the patch submitted by @marvinthepa.  I didn't come across any issues running it on my end, but please see if this patch fixes the issues you're coming across.

**Comment by jlwt90** [comment]
@marvinthepa thanks! I think it's fixed already!
