### ISSUE TITLE
Recently lost the ability to trigger Jenkins builds from PRs

### ISSUE THREAD

**Issue by coreycsteele** [mohamicorp/stash-jenkins-postreceive-webhook#205]
Bitbucket Server Webhook to Jenkins, the Advanced Configuration used to have an option to trigger jenkins for all pull requests. Recently this option disappeared. Please bring it back.

My preferred config, which worked until recently, is to have Bitbucket only trigger Jenkins on pull request changes and on special branches (“Build from”). Now only the latter is an option.

Looks like the only workaround is to “Build all”, but that will cause extra load on our jenkins bots performing work on branches not ready to be reviewed.

**Comment by coreycsteele** [comment]
The person reporting this issue to me found that this actually does work.  Issue filed in error.

**Comment by mdavoodi** [comment]
Thanks for closing the issue. As a reminder, we've moved our issue tracking to JIRA, please file any new issues here:

https://mohamicorp.atlassian.net/servicedesk/

**Comment by coreycsteele** [comment]
I went off your marketplace page, the submit support request is pointing at github.  I’ll make a note of the new issue tracking page.  Thanks.

corey

**Comment by mdavoodi** [comment]
Thanks for the heads up, we've changed the URL now.

**Comment by coreycsteele** [comment]
I’m trying to get a password reset link from your site but I’m not receiving anything.  Is that working?  Your docs indicated you can setup multiple jenkins url’s but the button to do that doesn’t exist.

corey

**Comment by mdavoodi** [comment]
Hi Corey,

The password reset should be handled by Atlassian (they host our service desk and jira), not sure why it's not working at the moment. 

As for the multi-server support, we're releasing a new version of the plugin today which will include that. We published the new documentation a little early. You'll be able to get it today.

Mohammed
